name: Build
on:
  push:
    branches: [ "**" ]
  pull_request:
  workflow_dispatch: 

jobs:
  test:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    name: Test
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew
      
      - uses: actions/setup-java@v4
        with:
          java-version: 22
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Execute Gradle build
        run: ./gradlew build --no-daemon --stacktrace -x test
